# Generated by Django 2.2.5 on 2020-10-22 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JTBCService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('program_title', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
                ('detail_type', models.CharField(max_length=20)),
                ('service_title', models.CharField(max_length=64)),
                ('repeat_info', models.TextField()),
                ('result_info', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 4, 38, 744705, tzinfo=utc))),
                ('countdown', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('process_result', models.BooleanField(default=True, verbose_name='process result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KBS1Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('program_title', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
                ('detail_type', models.CharField(max_length=20)),
                ('service_title', models.CharField(max_length=64)),
                ('repeat_info', models.TextField()),
                ('result_info', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 4, 38, 744705, tzinfo=utc))),
                ('countdown', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('process_result', models.BooleanField(default=True, verbose_name='process result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KBS2Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('program_title', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
                ('detail_type', models.CharField(max_length=20)),
                ('service_title', models.CharField(max_length=64)),
                ('repeat_info', models.TextField()),
                ('result_info', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 4, 38, 744705, tzinfo=utc))),
                ('countdown', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('process_result', models.BooleanField(default=True, verbose_name='process result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVNService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('program_title', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
                ('detail_type', models.CharField(max_length=20)),
                ('service_title', models.CharField(max_length=64)),
                ('repeat_info', models.TextField()),
                ('result_info', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 4, 38, 744705, tzinfo=utc))),
                ('countdown', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('process_result', models.BooleanField(default=True, verbose_name='process result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TvServiceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=20)),
                ('participants', models.IntegerField()),
                ('result', models.TextField()),
            ],
        ),
    ]
