# Generated by Django 2.2.5 on 2020-10-22 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtbcservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 42, 56, 306617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbs1service',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 42, 56, 306617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbs2service',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 42, 56, 306617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tvnservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 42, 56, 306617, tzinfo=utc)),
        ),
    ]
