# Generated by Django 2.2.5 on 2020-11-05 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201105_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelservice1',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice10',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice11',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice12',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice13',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice14',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice15',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice16',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice2',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice3',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice4',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice5',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice6',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice7',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice8',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='channelservice9',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jtbcservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbs1service',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbs2service',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mbcservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sbsservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tvnservice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 41, 56, 536361, tzinfo=utc)),
        ),
    ]
